//! `starling-proto`: the Mumble wire protocol, server side.
//!
//! This crate is deliberately I/O-free and state-free. It knows how to turn
//! bytes into messages and messages into bytes, and nothing else. Everything
//! that decides *what* to send lives in `starling-server`.
//!
//! # Scope
//!
//! * [`proto`]: `prost`-generated types for `Mumble.proto` / `MumbleUDP.proto`.
//! * [`message`]: the [`ControlMessage`] enum and the message-type-id table
//!   shared by both directions of the TCP control channel.
//! * [`codec`]: the `[type:u16][len:u32][payload]` TCP framing.
//! * [`version`]: Mumble's two version encodings plus the Fancy extension
//!   version.
//!
//! # Hostile input
//!
//! Unlike the client's `mumble-protocol`, everything here decodes data from an
//! *unauthenticated peer*. Decoders must bound allocations before making them
//! and must never panic on malformed input, see [`codec::decode`].

/// `prost`-generated protobuf message types.
///
/// Both modules below carry the same `allow` list, and it is `allow` and not
/// `expect` for both: which doc lints fire depends on how upstream wrapped the
/// `.proto` comments, so an unfulfilled `expect` would break the build on an
/// unrelated upstream rewrap. Each list is the measured minimum.
pub mod proto {
    /// Generated types for the Mumble TCP control protocol (`Mumble.proto`).
    #[allow(
        missing_docs,
        missing_debug_implementations,
        clippy::doc_markdown,
        clippy::doc_lazy_continuation,
        clippy::too_many_lines,
        clippy::allow_attributes_without_reason,
        rustdoc::bare_urls,
        rustdoc::invalid_html_tags,
        reason = "generated by prost-build; not hand-written and not editable"
    )]
    pub mod tcp {
        include!(concat!(env!("OUT_DIR"), "/mumble_proto.rs"));
    }

    /// Generated types for the Mumble UDP audio protocol (`MumbleUDP.proto`).
    #[allow(
        missing_docs,
        missing_debug_implementations,
        clippy::doc_markdown,
        clippy::doc_lazy_continuation,
        clippy::too_many_lines,
        clippy::allow_attributes_without_reason,
        rustdoc::bare_urls,
        rustdoc::invalid_html_tags,
        reason = "generated by prost-build; not hand-written and not editable"
    )]
    pub mod udp {
        include!(concat!(env!("OUT_DIR"), "/mumble_udp.rs"));
    }
}

pub mod codec;
pub mod error;
pub mod message;
pub mod version;

pub use error::{Error, Result};
pub use message::{ControlMessage, TcpMessageType};
pub use version::{MUMBLE_VERSION, Version};
