//! Starling's native TOML configuration.
//!
//! Every field is optional, so a config file states only what it changes and the
//! rest comes from the layer beneath (see [`ConfigSource`]'s contract). Unknown
//! keys are **rejected**, not ignored: a typo in a server config should fail
//! loudly at startup rather than quietly leave a limit at its default.

use serde::{Deserialize, Serialize};
use starling_config::{Limits, ServerConfig};

use starling_log::LogConfig;

use crate::{ConfigSource, Settings, TlsSettings};

/// A parsed `starling.toml`.
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct NativeConfig {
    /// Identity and network binding.
    pub server: ServerSection,
    /// Capacity and size limits.
    pub limits: LimitsSection,
    /// Optional behaviour.
    pub features: FeaturesSection,
    /// TLS identity paths.
    pub tls: TlsSection,
    /// Where log records go.
    pub logging: Option<LogConfig>,
}

/// `[server]`
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct ServerSection {
    /// Address to bind (murmur: `host`).
    pub host: Option<String>,
    /// TCP port (murmur: `port`).
    pub port: Option<u16>,
    /// Public server name, also the root channel's name (murmur: `registerName`).
    pub name: Option<String>,
    /// Message shown to clients on connect (murmur: `welcometext`).
    pub welcome_text: Option<String>,
    /// Password required to connect; empty means none (murmur: `serverpassword`).
    pub password: Option<String>,
}

/// `[limits]`
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct LimitsSection {
    /// Maximum concurrent users (murmur: `users`).
    pub max_users: Option<u32>,
    /// Total bandwidth budget in bits/sec (murmur: `bandwidth`).
    pub max_bandwidth: Option<u32>,
    /// Maximum chat message length in bytes (murmur: `textmessagelength`).
    pub max_text_message_bytes: Option<u32>,
    /// Maximum image message length in bytes (murmur: `imagemessagelength`).
    pub max_image_message_bytes: Option<u32>,
}

/// `[features]`
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct FeaturesSection {
    /// Whether chat messages may contain HTML (murmur: `allowhtml`).
    pub allow_html: Option<bool>,
    /// Whether clients may announce that they are recording.
    pub allow_recording: Option<bool>,
}

/// `[tls]`
#[derive(Debug, Default, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields, default)]
pub struct TlsSection {
    /// Certificate chain PEM path.
    pub certificate: Option<String>,
    /// Private key PEM path.
    pub key: Option<String>,
}

impl NativeConfig {
    /// Parse `starling.toml` contents.
    pub fn parse(contents: &str) -> Result<Self, toml::de::Error> {
        toml::from_str(contents)
    }

    /// Render fully-resolved settings as a `starling.toml`.
    ///
    /// Used by `starling migrate-config` to turn a murmur `.ini` into the
    /// native format. Every value is written explicitly: the point of a
    /// migration is to make what you were relying on visible.
    pub fn render(settings: &Settings) -> String {
        let server = &settings.server;
        let config = Self {
            server: ServerSection {
                host: Some(server.host.clone()),
                port: Some(server.port),
                name: Some(server.register_name.clone()),
                welcome_text: Some(server.limits.welcome_text.clone()),
                password: Some(server.server_password.clone()),
            },
            limits: LimitsSection {
                max_users: Some(server.limits.max_users),
                max_bandwidth: Some(server.limits.max_bandwidth),
                max_text_message_bytes: Some(server.limits.max_text_message_length),
                max_image_message_bytes: Some(server.limits.max_image_message_length),
            },
            features: FeaturesSection {
                allow_html: Some(server.limits.allow_html),
                allow_recording: Some(server.limits.allow_recording),
            },
            tls: TlsSection {
                certificate: Some(settings.tls.certificate.display().to_string()),
                key: Some(settings.tls.key.display().to_string()),
            },
            logging: Some(settings.logging.clone()),
        };

        let body = toml::to_string_pretty(&config)
            .unwrap_or_else(|e| format!("# failed to render configuration: {e}\n"));
        format!("# Generated by `starling migrate-config`.\n{body}")
    }
}

impl ConfigSource for NativeConfig {
    fn name(&self) -> &'static str {
        "starling.toml"
    }

    fn apply(&self, settings: Settings) -> Settings {
        let base = settings.server;
        Settings {
            server: ServerConfig {
                host: self.server.host.clone().unwrap_or(base.host),
                port: self.server.port.unwrap_or(base.port),
                register_name: self.server.name.clone().unwrap_or(base.register_name),
                server_password: self.server.password.clone().unwrap_or(base.server_password),
                limits: Limits {
                    max_users: self.limits.max_users.unwrap_or(base.limits.max_users),
                    max_bandwidth: self
                        .limits
                        .max_bandwidth
                        .unwrap_or(base.limits.max_bandwidth),
                    welcome_text: self
                        .server
                        .welcome_text
                        .clone()
                        .unwrap_or(base.limits.welcome_text),
                    allow_html: self.features.allow_html.unwrap_or(base.limits.allow_html),
                    max_text_message_length: self
                        .limits
                        .max_text_message_bytes
                        .unwrap_or(base.limits.max_text_message_length),
                    max_image_message_length: self
                        .limits
                        .max_image_message_bytes
                        .unwrap_or(base.limits.max_image_message_length),
                    allow_recording: self
                        .features
                        .allow_recording
                        .unwrap_or(base.limits.allow_recording),
                },
            },
            tls: TlsSettings {
                certificate: self
                    .tls
                    .certificate
                    .as_ref()
                    .map_or(settings.tls.certificate, Into::into),
                key: self.tls.key.as_ref().map_or(settings.tls.key, Into::into),
            },
            logging: self.logging.clone().unwrap_or(settings.logging),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(contents: &str) -> NativeConfig {
        NativeConfig::parse(contents).expect("valid TOML")
    }

    #[test]
    fn an_empty_file_changes_nothing() {
        // The layering contract: a file that says nothing must not reset the
        // layer beneath it.
        let base = Settings {
            server: ServerConfig {
                port: 9999,
                register_name: "Kept".into(),
                ..Default::default()
            },
            ..Default::default()
        };
        let applied = parse("").apply(base.clone());
        assert_eq!(applied.server.port, 9999);
        assert_eq!(applied.server.register_name, "Kept");
        assert_eq!(applied.tls, base.tls);
    }

    #[test]
    fn a_partial_file_only_changes_what_it_names() {
        let base = Settings {
            server: ServerConfig {
                port: 9999,
                limits: Limits {
                    max_users: 42,
                    ..Default::default()
                },
                ..Default::default()
            },
            ..Default::default()
        };
        let applied = parse("[server]\nport = 1234\n").apply(base);
        assert_eq!(applied.server.port, 1234);
        assert_eq!(
            applied.server.limits.max_users, 42,
            "untouched setting was reset"
        );
    }

    #[test]
    fn a_full_file_resolves_every_section() {
        let applied = parse(
            r#"
[server]
host = "0.0.0.0"
port = 64738
name = "Fancy Mumble e2e"
welcome_text = "<b>Hello</b>"
password = "hunter2"

[limits]
max_users = 100
max_bandwidth = 320000
max_text_message_bytes = 131072
max_image_message_bytes = 10485760

[features]
allow_html = true
allow_recording = false

[tls]
certificate = "/etc/starling/cert.pem"
key = "/etc/starling/key.pem"
"#,
        )
        .apply(Settings::default());

        assert_eq!(applied.server.host, "0.0.0.0");
        assert_eq!(applied.server.port, 64738);
        assert_eq!(applied.server.register_name, "Fancy Mumble e2e");
        assert_eq!(applied.server.limits.welcome_text, "<b>Hello</b>");
        assert!(applied.server.requires_password());
        assert_eq!(applied.server.limits.max_users, 100);
        assert_eq!(applied.server.limits.max_bandwidth, 320_000);
        assert_eq!(applied.server.limits.max_text_message_length, 131_072);
        assert_eq!(applied.server.limits.max_image_message_length, 10_485_760);
        assert!(applied.server.limits.allow_html);
        assert!(!applied.server.limits.allow_recording);
        assert_eq!(
            applied.tls.certificate,
            std::path::PathBuf::from("/etc/starling/cert.pem")
        );
    }

    #[test]
    fn an_unknown_key_is_rejected_rather_than_ignored() {
        // A typo in a server config must fail at startup, not silently leave a
        // limit at its default.
        let err = NativeConfig::parse("[server]\nprot = 64738\n")
            .expect_err("unknown keys must be rejected");
        assert!(err.to_string().contains("prot"), "{err}");
    }

    #[test]
    fn an_unknown_section_is_rejected() {
        assert!(NativeConfig::parse("[nonsense]\nx = 1\n").is_err());
    }

    #[test]
    fn a_wrongly_typed_value_is_rejected() {
        assert!(NativeConfig::parse("[server]\nport = \"64738\"\n").is_err());
    }

    #[test]
    fn an_empty_password_is_distinguishable_from_an_absent_one() {
        // `password = ""` means "no password"; omitting the key means "keep
        // whatever the layer beneath decided".
        let base = Settings {
            server: ServerConfig {
                server_password: "inherited".into(),
                ..Default::default()
            },
            ..Default::default()
        };
        assert_eq!(
            parse("[server]\npassword = \"\"\n")
                .apply(base.clone())
                .server
                .server_password,
            ""
        );
        assert_eq!(parse("").apply(base).server.server_password, "inherited");
    }

    #[test]
    fn rendered_config_round_trips_through_the_parser() {
        // What `migrate-config` prints must be loadable, or the migration is a
        // dead end.
        let original = Settings {
            server: ServerConfig {
                register_name: "Fancy Mumble e2e".into(),
                port: 64738,
                limits: Limits {
                    welcome_text: "<b>Hi</b>".into(),
                    max_users: 100,
                    ..Default::default()
                },
                ..Default::default()
            },
            ..Default::default()
        };

        let rendered = NativeConfig::render(&original);
        let reparsed = NativeConfig::parse(&rendered)
            .expect("rendered config must parse")
            .apply(Settings::default());

        assert_eq!(reparsed.server.register_name, original.server.register_name);
        assert_eq!(
            reparsed.server.limits.welcome_text,
            original.server.limits.welcome_text
        );
        assert_eq!(reparsed.server.port, original.server.port);
        assert_eq!(
            reparsed.server.limits.max_users,
            original.server.limits.max_users
        );
        assert_eq!(reparsed.tls, original.tls);
    }

    #[test]
    fn rendered_config_is_commented_so_its_origin_is_obvious() {
        assert!(NativeConfig::render(&Settings::default()).starts_with('#'));
    }
}
