//! `starling-proto-fancy`: everything on the wire that upstream Mumble does
//! not define.
//!
//! Two kinds of contract live here, and they are deliberately in one crate
//! because they are both "ours to change":
//!
//! * **Fancy envelopes**, one outer message type per service, each carrying a
//!   service-owned `oneof`. Adding a message type touches one file and needs no
//!   gateway release (`docs/PROTOCOL-COMPATIBILITY.md` §3).
//! * **Inter-service gRPC**, the contracts services speak to each other. No
//!   client ever sees these.
//!
//! What is *not* here is upstream `Mumble.proto`: it is frozen, it lives in
//! `starling-proto`, and nothing in this crate can reach it. That split is what
//! makes "never break a native Mumble client" structural rather than a rule
//! someone has to remember.

pub mod identity;
pub mod page;
pub mod perm;
pub mod types;

/// Generated code, one module per proto package.
///
/// `allow`, not `expect`: which doc lints fire depends on how the `.proto`
/// comments happened to wrap, so an unfulfilled `expect` would break the build
/// on an unrelated comment edit. The list is the measured minimum.
macro_rules! generated {
    ($(#[$doc:meta])* $name:ident, $package:literal) => {
        $(#[$doc])*
        #[allow(
            missing_docs,
            missing_debug_implementations,
            unreachable_pub,
            unused_qualifications,
            unused_results,
            clippy::doc_markdown,
            clippy::doc_lazy_continuation,
            clippy::large_enum_variant,
            clippy::too_many_lines,
            clippy::allow_attributes_without_reason,
            rustdoc::bare_urls,
            rustdoc::invalid_html_tags,
            reason = "generated by prost/tonic; not hand-written and not editable"
        )]
        pub mod $name {
            include!(concat!(env!("OUT_DIR"), "/", $package, ".rs"));
        }
    };
}

generated!(
    /// Types shared by more than one contract.
    common,
    "starling.common.v1"
);
generated!(
    /// The uniform gateway↔service client plane.
    control,
    "starling.control.v1"
);
generated!(
    /// The composed live view of connected sessions.
    sessionview,
    "starling.sessionview.v1"
);
generated!(
    /// Moderating a connected session: move, mute, deafen, suppress.
    sessioncontrol,
    "starling.sessioncontrol.v1"
);
generated!(
    /// Runtime-mutable operational settings.
    serverconfig,
    "starling.serverconfig.v1"
);
generated!(
    /// Readiness, per service and aggregated.
    health,
    "starling.health.v1"
);
generated!(
    /// The channel tree and membership.
    metadata,
    "starling.metadata.v1"
);
generated!(
    /// ACL evaluation.
    permissions,
    "starling.permissions.v1"
);
generated!(
    /// Registered accounts, profiles and blobs.
    userdata,
    "starling.userdata.v1"
);
generated!(
    /// Voice's control surface, never audio.
    voice,
    "starling.voice.v1"
);
generated!(
    /// Bans and kicks.
    moderation,
    "starling.moderation.v1"
);
generated!(
    /// Non-encrypted chat history.
    text,
    "starling.text.v1"
);
generated!(
    /// The hash-chained operator record.
    audit,
    "starling.audit.v1"
);
generated!(
    /// Signed URLs for bulk transfer.
    files,
    "starling.files.v1"
);
generated!(
    /// Push notifications.
    push,
    "starling.push.v1"
);
generated!(
    /// The plugin host and its key/value capability.
    plugins,
    "starling.plugins.v1"
);
generated!(
    /// Context-menu entries and the triggers back. Ice's `ServerContextCallback`.
    contextactions,
    "starling.contextactions.v1"
);

/// Client-facing envelopes, one module per owning service.
pub mod fancy {
    generated!(
        /// Primitives shared by more than one envelope; owns no outer type.
        wire,
        "starling.fancy.wire.v1"
    );
    generated!(
        /// Outer type 1000.
        session,
        "starling.fancy.session.v1"
    );
    generated!(
        /// Outer types 1001, 1002, 1003 and 1013.
        domain,
        "starling.fancy.domain.v1"
    );
    generated!(
        /// Outer types 1004, 1005, 1007, 1010, 1011, 1012, 1014, 1016 and 1017.
        feature,
        "starling.fancy.feature.v1"
    );
    generated!(
        /// Outer type 1006.
        pchat,
        "starling.fancy.pchat.v1"
    );
    generated!(
        /// Outer type 1015.
        social,
        "starling.fancy.social.v1"
    );
    generated!(
        /// Outer type 1008.
        screenshare,
        "starling.fancy.screenshare.v1"
    );
    generated!(
        /// Outer type 1009.
        files,
        "starling.fancy.files.v1"
    );
}

pub use perm::Perm;
pub use types::{OuterType, ServiceKind};
